# Generated by Django 5.1.6 on 2025-03-27 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_remove_grouprequest_sender_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='group_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.grouprequest'),
        ),
        migrations.AlterField(
            model_name='grouprequest',
            name='invited_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='received_group_requests', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
