# Generated by Django 5.1.6 on 2025-03-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_notification_group_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='extra_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
