# Generated by Django 5.1.6 on 2025-03-28 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_groupprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupProfile',
        ),
    ]
