# Generated by Django 5.1.6 on 2025-03-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_groupprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
