# Generated by Django 5.1.6 on 2025-03-28 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_alter_groupprofile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupprofile',
            name='members',
        ),
    ]
