# Generated by Django 5.1.6 on 2025-03-28 12:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_remove_groupprofile_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofile',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='group_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
