# Generated by Django 5.1.6 on 2025-03-28 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_groupprofile_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='extra_data',
        ),
        migrations.DeleteModel(
            name='GroupProfile',
        ),
    ]
