# Generated by Django 5.1.6 on 2025-03-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_remove_notification_extra_data_delete_groupprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='extra_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
