# Generated by Django 5.1.6 on 2025-04-01 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_delete_groupprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_profile_image', models.ImageField(default='group_avatars/group_default.png', upload_to='group_avatars/')),
                ('group_bio', models.TextField(blank=True, max_length=500)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='frontend.group')),
                ('group_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_admins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
