# Generated by Django 5.1.6 on 2025-04-01 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0016_groupprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 4, 1, 10, 7, 28, 181951, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
