# Generated by Django 5.1.6 on 2025-04-01 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0017_groupprofile_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupprofile',
            old_name='group_profile_image',
            new_name='group_avatar',
        ),
    ]
