# Generated by Django 5.1.6 on 2025-04-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0018_rename_group_profile_image_groupprofile_group_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
