# Generated by Django 5.1.6 on 2025-04-10 09:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0020_remove_group_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='audio',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='raw'),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='group_avatar',
            field=cloudinary.models.CloudinaryField(default='group_avatars/group_default.png', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='message',
            name='audio',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='message',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='raw'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='avatars/default.png', max_length=255, verbose_name='image'),
        ),
    ]
