# Generated by Django 5.1.6 on 2025-04-11 05:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0022_remove_message_file_message_file_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='file_image',
        ),
        migrations.RemoveField(
            model_name='message',
            name='file_raw',
        ),
        migrations.AddField(
            model_name='message',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
