# Generated by Django 5.1.6 on 2025-04-11 06:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0023_remove_message_file_image_remove_message_file_raw_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
    ]
