# Generated by Django 5.1.6 on 2025-04-11 11:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0025_alter_groupmessage_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='audio',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='audio'),
        ),
        migrations.AlterField(
            model_name='message',
            name='audio',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='audio'),
        ),
    ]
