# Generated by Django 5.1.6 on 2025-04-11 12:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0026_alter_groupmessage_audio_alter_message_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='avatars/default', max_length=255, verbose_name='image'),
        ),
    ]
